spring.application.name=bookshop-service

spring.config.import=optional:configserver:http://localhost:8888

# Fallback local config (used when Config Server is down)
spring.datasource.url=jdbc:h2:file:./Database/Data/bookshopdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console