server.port=8089

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/job_ms
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=30
eureka.client.initial-instance-info-replication-interval-seconds=30

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}

# Orders messaging
app.rabbitmq.orders.exchange=bookshop.orders.exchange
app.rabbitmq.orders.create.queue=orders.create.queue
app.rabbitmq.orders.create.routing-key=orders.create
