spring.application.name=Candidat4TWIN2Ms
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=false
server.port=8089
spring.cloud.config.enabled=false
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/job_ms
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=30
eureka.client.initial-instance-info-replication-interval-seconds=30